name: Deploy app (dev)
on:
  push:
    branches:
      - 'next'
  workflow_dispatch:
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install
        run: npm install
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: Checkout Ansible
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: thefirstspine/ansible
      - name: Get config
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: thefirstspine/ansible-secrets-dev
          path: tmp
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Get inventory
        run: |
          rm -rf volume/conf
          rm -rf volume/keys
          mv tmp/conf volume/conf
          mv tmp/keys volume/keys
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build thefirstspine/ansible image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: thefirstspine/ansible
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run thefirstspine/ansible image
        run: |
          docker run --rm -v ./volume:/volume -e BRANCH=next thefirstspine/ansible ansible-playbook -i /volume/conf/inventory.yaml /volume/playbooks/deploy-matches.yaml
